dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install pipenv
  - pipenv lock -r -d > Requirements.txt
  - pipenv lock -r  >> Requirements.txt
install:
  - pip install -r Requirements.txt
script:
  - isort -c
  - black --check --line-length=90 --target-version=py36 .
  - pyroma .
  - pylint --rcfile=setup.cfg collect_stata tests
  - pytest -rf --cov
